### ISSUE TITLE
do we have an example of syn watch?

### ISSUE THREAD

**Issue by danielzhanghl** [nokia/etcd-cpp-apiv3#8]
hi,  all the watch operation examples are asynchronous, do we have a way to sync the watch?
I tried below, but it return right way, instead of block there.
thanks for any suggestions!

static std::string etcd_uri("http: 127.0.0.1:2379");
    etcd::Client etcd(etcd_uri);
    etcd::Response response;
    pplx::task<etcd::Response> response_task = etcd.watch("/test/key1",true);
 try
  {
    std::cout << "start watch" << std::endl;
    response = response_task.get(); // can throw
    if (response.is_ok())
      std::cout << "successful action is: "<<response.action()<<"  value= " << response.value().as_string()  << std::endl;
    else
      std::cout << "operation failed, details: " << response.error_message();
  }
  catch (std::exception const & ex)
  {
    std::cerr << "communication problem, details: " << ex.what();
  }

---------
result is as below:

start watch
successful action is:   value=

**Comment by danielzhanghl** [comment]
after some dig into the code, it seems the watch can not be cancelled, that is a bug.

**Comment by sighingnow** [comment]
Hi @danielzhanghl,

You could find sync-watch examples in https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/a00a06d5bd09150b7e9d6ec8e8c3d3d7f5ce9d89/tst/EtcdSyncTest.cpp#L111-L179.
